config/routes.rb
Cliff::Application.routes.draw do

  ActiveAdmin.routes(self)

  devise_for :admin_users, ActiveAdmin::Devise.config

	match '/auth/:provider/callback' => 'authentications#create'
  authenticated :user do
    root :to => 'home#index'
  end

  get "/home/my_list", :as => "home"
  get "/home/faq", as: "faq"
  get "/home/self", as: "self"
  get "/home/testone"
  get "/home/testtwo"
  get "/home/resultone"
  get "/home/resulttwo"
  get "/home/result"
  get "/home/final_result"
  get "/home/report"
  post "/home/update_list1"
  post "/home/update_list2"

  root :to => "home#index"
  devise_for :users, :controllers => {:registrations => 'registrations'}
  resources :users, :only => :show
  resources :authentications

end

app/views/layouts/_navigation.html.haml
= link_to "Cliff", root_path, :class => 'brand'
%ul.nav
  - if user_signed_in?
    %li
      = link_to('Logout', destroy_user_session_path, :method=>'delete')
  - else
    %li
      = link_to('Login', new_user_session_path)
  - if user_signed_in?
    %li
      = link_to('Edit account', edit_user_registration_path)
  - else
    %li
      = link_to('Sign up', new_user_registration_path)

app/views/layouts/_navigation.html.slim
= link_to "Startup Quotient", home_path, :class => 'brand'
- if user_signed_in?
  ul.nav
    li
      = link_to(raw("<span class='#{ @edit_account_tab }'>Profile</span>"), edit_user_registration_path)
    li
      = link_to raw("<span class='#{ @test_one_tab }'>Part-One</span>"), home_testone_path
    li
      = link_to raw("<span class='#{ @test_two_tab }'>Part-Two</span>"), home_testtwo_path
    li
      = link_to raw("<span class='#{ @final_result_tab }'>Report</span>"), :controller => 'home', :action => "final_result"


ul.nav.pull-right
  li
    = link_to(raw("<span class='#{ @edit_account_tab }'>FAQs</span>"), faq_path)
  - if user_signed_in?
    li
      = link_to(raw("<span class='#{ @edit_account_tab }'>Self-Learning</span>"), self_path)
    li
      = link_to(raw("<span>Logout</span>"), destroy_user_session_path, :method=>'delete')
  - else
    li
      = link_to(raw("<span class='#{ @login_tab }'>Login</span>"), new_user_session_path)

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:charset => "utf-8"}
    %meta{"http-equiv" => "X-UA-Compatible", :content => "IE=edge,chrome=1"}
    %meta{:name => "viewport", :content => "width=device-width, initial-scale=1, maximum-scale=1"}
    %title= content_for?(:title) ? yield(:title) : "Cliff"
    %meta{:content => "", :name => "description"}
    %meta{:content => "", :name => "author"}
    = stylesheet_link_tag    "application", :media => "all"
    = javascript_include_tag "application"
    = javascript_include_tag "http://ajax.googleapis.com/ajax/libs/jquery/1.5/jquery.min.js"
    = javascript_include_tag "http://ajax.googleapis.com/ajax/libs/jqueryui/1.8/jquery-ui.min.js"
    = csrf_meta_tags
    = yield(:head)
  %body
    %header.navbar.navbar-fixed-top
      %nav.navbar-inner
        .container
          = render 'layouts/navigation'
    #main{:role => "main"}
      .container
        - flash.each do |name, msg|
          %div{:class => "alert alert-#{name == :notice ? "success" : "error"}"}
            %a.close{"data-dismiss" => "alert"} ×
            = msg

        = yield
        .clearfix
        %footer